### ISSUE TITLE
No Rift

### ISSUE THREAD

**Issue by TeCoEd** [WayneKeenan/python-vrzero#1]
Great work, I really like this and my students have been asking about VR on the Pi.  What are the outcomes if I do not have a Rift?  Can I still view output via an HDMI monitor (obviously it will not be truly immersive!) Does the controller movement still work?  Thanks

**Comment by WayneKeenan** [comment]
Thanks, hope you and your students have fun.

It will run fine without a Rift and plugged into a HDMI monitor; you can look around using the mouse or an Xbox controller fine.  The video was, badly, filmed on an iPhone pointed at an HDMIPi screen. :)

Please copy 'config/config_DK1.txt' to '/etc/config.txt' as that uses a resolution most HDMI screens will support by default, the DK2 config file is a bit more demanding.

All the best
Wayne

**Comment by WayneKeenan** [comment]
An enhancement would be to make it easy to turn off the barrel shader (used for Rift HMD lens distortion correction) and use the default pi3d shader in conjunction with a cardboard viewer or using the 'cross-eyed' method.

**Comment by WayneKeenan** [comment]
Please see the comments at the top of the abbey.py demo for an example of how to switch to 'plain HDMI monitor' (`use_simple_display`) mode
