### ISSUE TITLE
CV1 Support

### ISSUE THREAD

**Issue by Josh-1050** [WayneKeenan/python-vrzero#10]
looking to use this project for the basis of my own but using a CV1 has anyone looked at this before?

**Comment by WayneKeenan** [comment]
I’ve not got one, or know anyone with one, so I haven’t

**Comment by Josh-1050** [comment]
Right ok well I'll start with your DK2 settings and work from there, if I get it working I'll let you know!

**Comment by WayneKeenan** [comment]
OK cool, looking forward to hearing how you get on. Thanks!

**Comment by grindash** [comment]
Hi, I'm also trying to use a more recent oculus model (HM-A) but without success.
I was wondering if @Josh-1050 had succed to support the CV1.
