### ISSUE TITLE
what to do to run on x86?

### ISSUE THREAD

**Issue by assadollahi** [WayneKeenan/python-vrzero#11]
hi, thanks for the awesome work! 
i successfully ran your package on raspberry, now i'm trying to run it on x86.
to make things simple (or more compatible?), installed raspbian strech x86 version on my x86 machine.
i went through your instructions and it seemed to me that the only arm-dependent package is openhmd. so i installed the x86 version like so:

   95  wget http://ftp.us.debian.org/debian/pool/main/libo/libopenhmd/libopenhmd0_0.2.0-5_i386.deb
   96  cd ..
   97  sudo dpkg -i install/libopenhmd0_0.2.0-5_i386.deb
   98  sudo apt-get install -f
   99  sudo ldconfig

when running abbey.py demo, i get:
Traceback (most recent call last):
  File "./abbey.py", line 7, in <module>
    from vrzero import engine
  File "/usr/local/lib/python3.5/dist-packages/vrzero-0.0.1-py3.5.egg/vrzero/__init__.py", line 2, in <module>
    from .vrzero import (
  File "/usr/local/lib/python3.5/dist-packages/vrzero-0.0.1-py3.5.egg/vrzero/vrzero.py", line 6, in <module>
    from .hmd import OpenHMD
  File "/usr/local/lib/python3.5/dist-packages/vrzero-0.0.1-py3.5.egg/vrzero/hmd.py", line 18, in <module>
    lib = cdll.LoadLibrary('libopenhmd.so')
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenhmd.so: cannot open shared object file: No such file or directory

"whereis libopenhmd.so" doesn't deliver anything...
any clue, what to do?

**Comment by WayneKeenan** [comment]
It might be library version/naming, perhaps building from source will work, does issue #7 help you?

**Comment by assadollahi** [comment]
actually, changing the hmd.py file to .so.0 allowed me to start the demo without errors, as the OP of #7 suggested. however, now both, hmd as well as monitor turn black and i can't get out there anymore. did a remote login to reboot the machine. should i try to use the fork, you made in #7 ?

**Comment by WayneKeenan** [comment]
It's been a long time and this project isn't my main focus anymore so all I can suggest is give it a try.

**Comment by assadollahi** [comment]
thanks for that project, it was fun.
