### ISSUE TITLE
Update to latest Pi3D API

### ISSUE THREAD

**Issue by lazuli2393** [WayneKeenan/python-vrzero#12]
I followed your install instructions, but when I run a demo it gives the error
>assert self.context != EGL_NO_CONTEXT
it says it's in the pi3d DisplayOpenGL.py file.

I tried with the latest Raspberry Pi OS on a Pi 400 and Pi 3B.
If you could update the instructions and files to run on current software, I would greatly appreciate it.

**Comment by WayneKeenan** [comment]
It would appear that Pi3d has been updated to match the latest graphics system changes in Raspbian but my code is pinned to an older version of pi3d for API compatibility.  

The fix for this will require some investigation on my part.    

An alternative/workaround until that work is done, although not ideal, is to install an older Raspbian on your Pi3 (e.g. Jessie).

**Comment by lazuli2393** [comment]
Thank you for responding. I'll see if I can find a fix, but I doubt I will get very far.

Also, what would it take to use an entirely different rendering method? After following the steps, anything that can access OpenHMD and display a side-by-side 3D image should work?

**Comment by WayneKeenan** [comment]
I had a thought, have you tried the SonyPSVR_WIP branch? (No promises. I haven't had chance to check it on a device recently)

In theory, I suppose so. 


I've recently purchased a Pi 400 and intend/plan/hope to get the master working with it and my PSVR headset.

**Comment by WayneKeenan** [comment]
I've just taken a look at this and have gotten a bit further, but not fixed it.  

Based on the info here: 

1. https://pi3d.github.io/html/ReadMe.html#setup-on-the-raspberry-pi
2. https://pi3d.github.io/html/FAQ.html

On my Pi4 (using a Pi4 is important) I had todo:

1. `sudo pip3 install pi3d`       (i.e. not the 2.14 pinned version, so expecting API issues later, but it's necessary for OpenGL setup on a Pi4)
2. select the 'fake KMS' driver using `raspi-config`
3. launch the vrzero demos from a terminal on the desktop   (see link 1 for more info)

That gets over your original (and a couple of subsequent) issues; a render window briefly pops up, but I now get an assertion:

```
pi@pivr:~/projects/vrzero/demos $ python3 blockworld.py 
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "blockworld.py", line 16, in <module>
    engine.init()
  File "/usr/local/lib/python3.7/dist-packages/vrzero-0.0.1-py3.7.egg/vrzero/vrzero.py", line 134, in init
    self.DISPLAY = pi3d.Display.create(w=self.hmd_screen_width, h=self.hmd_screen_height, use_pygame=True)
  File "/usr/local/lib/python3.7/dist-packages/pi3d/Display.py", line 570, in create
    display_config=display_config, window_title=window_title, use_glx=use_glx)
  File "/usr/local/lib/python3.7/dist-packages/pi3d/util/DisplayOpenGL.py", line 121, in create_display
    self.create_surface(x, y, w, h, layer)
  File "/usr/local/lib/python3.7/dist-packages/pi3d/util/DisplayOpenGL.py", line 325, in create_surface
    assert r
AssertionError
```

Will revisit this.

BTW the Pi3d demos I tried worked ok, so vrzero needs bringing up to date with the latest Pi3d API.

**Comment by paddywwoof** [comment]
Wayne, I'll have a look at this now. There was quite a bit of hair tearing when the RPi4 appeared out of nowhere and the broadcom graphics bcm_host display surface disappeared! I see your error has use_pygame=True which might be an issue. On RPi4 I think you have to use X for the surface.

PS I've just done a couple of tests on my RPi4 and I seem to get the same error when trying to run with ```use_pygame=True```. Do you need pygame for this project? You look to use the InputEvents system.

**Comment by WayneKeenan** [comment]
Ah, thanks Paddy, I just noticed this too, I updated 'your repo' ticket, it's something todo with the camera(s) rendering to a texture before display.  
I do need joypad and keyboard input, I'll happily switch to something non-pygame outside of Pi3d to get input events, so don't worry about that.

**Comment by WayneKeenan** [comment]
Hiya @69K-ram , if you get a chance to try out the latest INSTALL.txt steps please let me know how it goes.  Feel free to re-open or raise a new issue if you run into trouble.

Thanks.
