### ISSUE TITLE
wrong message

### ISSUE THREAD

**Issue by SunshineJunFu** [WayneKeenan/python-vrzero#9]
when I call the function engine.init(), some wrong message shows as the following:

```
No handlers could be found for logger "pi3d.Display"
Traceback (most recent call last):
  File "abbey.py", line 17, in <module>
    engine.init()
  File "/home/fj/anaconda2/lib/python2.7/site-packages/vrzero-0.0.1-py2.7.egg/vrzero/vrzero.py", line 141, in init
    self.CAMERA = pi3d.StereoCam(separation=self.hmd_eye_seperation, interlace=0, shader=shader_name)
  File "build/bdist.linux-x86_64/egg/pi3d/util/StereoCam.py", line 42, in __init__
  File "build/bdist.linux-x86_64/egg/pi3d/Shader.py", line 106, in __init__
  File "build/bdist.linux-x86_64/egg/pi3d/Shader.py", line 93, in make_shader
  File "build/bdist.linux-x86_64/egg/pi3d/Shader.py", line 181, in _load_shader
IOError: [Errno 2] No such file or directory: u'barrel.vs'

```

**Comment by WayneKeenan** [comment]
I /think/ you have a version of Pi3d newer than 2.14 installed.  There was a change in a later version of Pi3d that the the pypi and master branch release haven't been updated to work with.

The WIP SonyPSVR branch has a fix for it,  but for simplicity sake you can you install Pi3d 2.14 ? e.g.:

```
sudo pip3 install pi3d==2.14
```

**Comment by SunshineJunFu** [comment]
It works well. I can watch the scene from desktop, but i can't see the scene in the oculus rift cv1. Are there some problems with rendering? 
`2018-04-20 12:45:05,959 WARNING: pi3d.Display: Do you need to install pygame?
('keyboards =', [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 12), (8, 16)])
('mice = ', [])
('joysticks =', [])
HMD Device found, vendor=None, product=None, path=None`

**Comment by WayneKeenan** [comment]
Although, I've never used a CV1 and can only suggest you try backing up your config.txt first before trying config_DK2.txt.   So there's the possibility it doesn't work.

So, have you modified your /boot/config.txt as mentioned in the Install steps in the README?

**Comment by WayneKeenan** [comment]
Also, the 'HMD Device found, vendor=None, product=None, path=None` doesn't look promising for reading head rotation data.

What version of OpenHMD are you using on which OS platform are you running?
